version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query account --output text)
      - REGION=ap-southeast-1
      - REPO_URI=699754982358.dkr.ecr.ap-southeast-1.amazonaws.com/doan/backend
      - IMAGE_TAG=latest
      - aws ecr get-login --region $REGION --no-include-email

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPO_URI:latest .
      - docker tag $REPO_URI:lastest $REPO_URI:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing image to ECR...
      - docker push $REPO_URI:lastest 
      - echo Writing image definitions file...
      - printf '[{"name":"doan","imageUri":"%s.dkr.ecr.%s.amazonaws.com/%s:%s"}]' $ACCOUNT_ID $REGION $REPO_NAME $IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
